package test1;
// Generated Jul 24, 2017 11:49:37 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Info generated by hbm2java
 */
public class Info  implements java.io.Serializable {


     private int userId;
     private String username;
     private String token;
     private Date createdOn;
     private String secretkey;
     private String lastConsumeToken;

    public Info() {
    }

    public Info(int userId, String username, String token, Date createdOn, String secretkey, String lastConsumeToken) {
       this.userId = userId;
       this.username = username;
       this.token = token;
       this.createdOn = createdOn;
       this.secretkey = secretkey;
       this.lastConsumeToken = lastConsumeToken;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public String getSecretkey() {
        return this.secretkey;
    }
    
    public void setSecretkey(String secretkey) {
        this.secretkey = secretkey;
    }
    public String getlastConsumeToken() {
        return this.lastConsumeToken;
    }
    
    public void setlastConsumeToken(String lastConsumeToken) {
        this.lastConsumeToken = lastConsumeToken;
    }




}


